<?php
if (($filmax_slider_sc = filmax_get_theme_option('front_page_title_shortcode')) != '' && strpos($filmax_slider_sc, '[')!==false && strpos($filmax_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$filmax_anchor_icon = filmax_get_theme_option('front_page_title_anchor_icon');	
		$filmax_anchor_text = filmax_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($filmax_anchor_icon) || !empty($filmax_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($filmax_anchor_icon) ? ' icon="'.esc_attr($filmax_anchor_icon).'"' : '')
											. (!empty($filmax_anchor_text) ? ' title="'.esc_attr($filmax_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($filmax_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$filmax_scheme = filmax_get_theme_option('front_page_title_scheme');
				if (!filmax_is_inherit($filmax_scheme)) echo ' scheme_'.esc_attr($filmax_scheme);
				echo ' front_page_section_paddings_'.esc_attr(filmax_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$filmax_css = '';
			$filmax_bg_image = filmax_get_theme_option('front_page_title_bg_image');
			if (!empty($filmax_bg_image)) 
				$filmax_css .= 'background-image: url('.esc_url(filmax_get_attachment_url($filmax_bg_image)).');';
			if (!empty($filmax_css))
				echo ' style="' . esc_attr($filmax_css) . '"';
	?>><?php
		// Add anchor
		$filmax_anchor_icon = filmax_get_theme_option('front_page_title_anchor_icon');	
		$filmax_anchor_text = filmax_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($filmax_anchor_icon) || !empty($filmax_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($filmax_anchor_icon) ? ' icon="'.esc_attr($filmax_anchor_icon).'"' : '')
											. (!empty($filmax_anchor_text) ? ' title="'.esc_attr($filmax_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (filmax_get_theme_option('front_page_title_fullheight'))
				echo ' filmax-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$filmax_css = '';
				$filmax_bg_mask = filmax_get_theme_option('front_page_title_bg_mask');
				$filmax_bg_color = filmax_get_theme_option('front_page_title_bg_color');
				if (!empty($filmax_bg_color) && $filmax_bg_mask > 0)
					$filmax_css .= 'background-color: '.esc_attr($filmax_bg_mask==1
																		? $filmax_bg_color
																		: filmax_hex2rgba($filmax_bg_color, $filmax_bg_mask)
																	).';';
				if (!empty($filmax_css))
					echo ' style="' . esc_attr($filmax_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$filmax_caption = filmax_get_theme_option('front_page_title_caption');
				if (!empty($filmax_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($filmax_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses($filmax_caption, 'filmax_kses_content' ); ?></h1><?php
				}
			
				// Description (text)
				$filmax_description = filmax_get_theme_option('front_page_title_description');
				if (!empty($filmax_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($filmax_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses(wpautop($filmax_description), 'filmax_kses_content' ); ?></div><?php
				}
				
				// Buttons
				if (filmax_get_theme_option('front_page_title_button1_link')!='' || filmax_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						filmax_show_layout(filmax_customizer_partial_refresh_front_page_title_button1_link());
						filmax_show_layout(filmax_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}